name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download ast-grep
        run: |
          curl "https://github.com/ast-grep/ast-grep/releases/download/0.27.0/app-x86_64-unknown-linux-gnu.zip" -L -o ast-grep.zip
          unzip ast-grep.zip
          ls -al
          chmod +x ast-grep
          chmod +x sg
          ls -al
          ./ast-grep --version
          ./sg --version
